### PR TITLE
add recommendation backend files

### PR DESCRIPTION
**Pull request by liminding-UCSB**
In this PR,

1. We copied Recommendation @entity from team02.
2. We copied Recommendation @repository from team02.
3. We copied Recommendation Controller from team02.
4. We copied Recommendation Controller tests from team02.

### CODE REVIEW

**Review by hyunkyumkim — APPROVED** [review]
LGTM

**Comment by jacksonjude** [comment]
Can you check tests locally again bc they seem to be failing here

**Review by jacksonjude — APPROVED** [review]
LGTM

**Review by anouki-p — APPROVED** [review]
lgtm

**Review by jaoviedo — APPROVED** [review]
LGTM

**Review by ryanlavu — APPROVED** [review]
LGTM

**Pull request merged**
