### PR TITLE
Ryan placeholder index

### PR DESCRIPTION
**Pull request by ryanlavu**
# Overview
To create a placeholder index page for Article, plus some tests

# Issues Addressed
#19

### CODE REVIEW

**Review by liminding-UCSB — APPROVED** [review]
LGTM

**Comment by jacksonjude** [comment]
Can we get the App.js changes reverted?

**Review by hyunkyumkim — APPROVED** [review]
LGTM

**Review by jacksonjude — APPROVED** [review]
LGTM

**Review by jaoviedo — APPROVED** [review]
LGTM

**Pull request merged**
